### ISSUE TITLE
Check 1.3 subtracts 0 when it passes

### ISSUE THREAD

**Issue by introllo** [docker/docker-bench-security#289]
https://github.com/docker/docker-bench-security/blob/master/tests/1_host_configuration.sh

# 1.3
...
  else
    pass "$check_1_3"
    info "     * Using $docker_version which is current"
    info "     * Check with your operating system vendor for support and security maintenance for Docker"
    logjson "1.3" "PASS"
    currentScore=$((currentScore - 0))
  fi
}

Why are we subtracting zero here? Is this desired behavior? It does throw off the $currentScore value (off-by-one). 

I like the JSON scoring feature - quick visual and trend (are we getting better?). I'd prefer the values to "match up". I have made a change in my fork. Happy to raise to a pull request if desired.

**Comment by konstruktoid** [comment]
The question about substracting 0 is a good one since currentScore could be `currentScore=$currentscore`, but my simply logic was if you pass a scored you'll get +1, fail -1 and a not scored test -0 since "failure to comply with "Not Scored" recommendations will not decrease the final benchmark score. Compliance with "Not Scored" recommendations will not increase the 
final benchmark score."

#290 will whoever not get merged since 1.3 is a "Not Scored" check.
