### ISSUE TITLE
Rule 2.13 no longer valid for Docker v17.12 and on

### ISSUE THREAD

**Issue by isuftin** [docker/docker-bench-security#309]
The --disable-legacy-registry flag is no longer supported by Docker since version v17.12 and on.

In order to meet rule 2.13, one would have to include this flag into the docker daemon options. However, Docker no longer starts once you do include that flag.

```
...
Jun 29 15:44:45 default-centos-7.vagrantup.com dockerd[29998]: ERROR: The '--disable-legacy-registry' flag has been removed. Interacting with legacy (v1) registries is no longer supported
Jun 29 15:44:45 default-centos-7.vagrantup.com systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 29 15:44:45 default-centos-7.vagrantup.com systemd[1]: Failed to start Docker Application Container Engine.
Jun 29 15:44:45 default-centos-7.vagrantup.com systemd[1]: Unit docker.service entered failed state.
Jun 29 15:44:45 default-centos-7.vagrantup.com systemd[1]: docker.service failed.
...
```

Perhaps check if the version of the daemon is v17.12 or later [here](https://github.com/docker/docker-bench-security/blob/master/tests/2_docker_daemon_configuration.sh#L286-L302) and pass if so, since it is always disabled with no option to enable it at that version and above.

**Comment by konstruktoid** [comment]
Hi and thanks @isuftin, this should be fixed in #311

**Comment by konstruktoid** [comment]
Closed since #311 has been merged.

**Comment by isuftin** [comment]
Thank you 👍

**Comment by src7** [comment]
Hello,

this test is a bit confusing because it returns always "INFO" since 1712.
Shouldn't it return PASS instead ? (since support for V1 registries has indeed been removed).
There is enough "INFOs" to take account of and some of them are really serious.

**Comment by src7** [comment]
Also I have serious doubts about the version comparison (because of `tr -d '[:alpha:]-,.'`).

For example, `18.06.3-ce` gives `18063` and is compared to `1712`.
If the string was `17.12.0-ce` for v12.17(.0), it would be `17120`.
`17.09.0-ce` would give `17090` and is greater than `1712` so there would be no warnings despite v17.09 has been released before v12.17.
 (I don't have such old versions to test now).

https://github.com/docker/docker-bench-security/blob/7aaebd63c45ebb74ed6448bc38e1fb21d152a47d/tests/2_docker_daemon_configuration.sh#L320

https://github.com/docker/docker-bench-security/blob/7aaebd63c45ebb74ed6448bc38e1fb21d152a47d/tests/2_docker_daemon_configuration.sh#L328

**Comment by src7** [comment]
Ok, now I understand why it returns "INFO" and not simply "PASS".

**Comment by konstruktoid** [comment]
Hi @src7, I've updated to `2.13` only uses year and month. Thanks for catching this.

```
$ docker version | grep -i -A2 '^server' | grep ' Version:' | awk '{print $NF; exit}' | tr -d '[:alpha:]-,.'
18093
$ docker version | grep -i -A2 '^server' | grep ' Version:' | awk '{print $NF; exit}' | tr -d '[:alpha:]-,.' | cut -c 1-4
1809
```
