### ISSUE TITLE
Automate testing

### ISSUE THREAD

**Issue by konstruktoid** [docker/docker-bench-security#348]
The testing is, more or less, a manual operation today.
This consequence of lack of testing are inconsistent output, and more than once have simple code changes caused incorrect results.
Verification of tests have also been forgotten.

https://github.com/docker/docker-bench-security/pull/343
https://github.com/docker/docker-bench-security/pull/345
https://github.com/docker/docker-bench-security/pull/347
https://github.com/docker/docker-bench-security/issues/286#issuecomment-441127060

**Comment by dxcSithLord** [comment]
I would like to propose an update to the bench testing structure that will aid in the resolution of this issue.  I very much like the way that this has been written, but looking at the code with fresh eyes, I see too much repeated code in every test, which leads to increased probability of coding errors/typos/inconsistent output.
What I propose is to replace the bulk of each check_x_y_z test (those that increment the total and result count) with a generic test function.  The arguments to the function are the id "x_y_z" and the description test.  Using the argument for the id, this can be appended to the string "check_" to call the remainder of the code that performs the test.  The only requirement of the trimmed down code is that it returns (for example) either 0 (pass) or not 0 (not pass).
This would allow for the individual tests to be executed in isolation testing prior to integration with the whole.
As this does not change the name of the final test code "check_x_y_z", the integration of this does not need to be all or nothing.
This also adds to the functions_lib.sh readability, since it will change from:
check_2_1_2
to :
make_check "2_1_2" "Test this function"

I have included a suggested code segment, which also includes a replacement for the check_n and check_n_m, where the test sections are started and descriptive headings are the only content.

`\#
\# This is a generic replacement for all the "check_*" functions that repeat most of the same code
\# reducing the overall length significantly and avoiding repeat errors
\#
\# The quoted values are from the grep string expression below
\# This assumes that the id reference is a string with
\# starting with (beginning of the line) "^"
\# number in the range 1-9 "[1-9]", followed by
\# zero or more digits 0-9 "[0-9]*", followed by
\# with zero or more of the following "(":
\# the single underscore character "_"
\# a number in the range 1-9 "[1-9]", followed by
\# zero or more digits in the range 0-9 "[0-9]*"
\# close sequence ")*"
\# terminating with the line end "$".
\# Any other test or spaces  before or after will cause the match to fail.
\# Possible matches include:
\# 1 2 3 4 5 6 7 8 9
\# 1_1 1_1_1 1_1_1_1
\# 10_1_2_3_4_50
\# 900_1_604
\# Not valid:
\# 0 leading zero
\# 1_ trailing underscore
\# 1_0 leading zero
\# 9_8_0 leading zero
\# 2_04 leading zero
\# The resulting function is a concatination of
\# check_ and $1
\# The id is the same, but with "_" replaced with "." character
\# The functions need to return 0 for success - anything else will
\# generate a warning

make_check() {
  if echo "$1" | grep -cwE '^[1-9][0-9]*(_[1-9][0-9]*)*$' -eq 1; then
    check_ref=$(echo "$1" | sed -e "s/_/./g")
    id_ref="$1"
    desc_ref="$2"
    check_desc="$check_ref - $desc_ref"
    starttestjson "$id_ref" "$desc_ref"

    totalChecks=$((totalChecks + 1))
    if check_${id_ref} -eq 0; then
      pass "$check_desc"
      resulttestjson "PASS"
      currentScore=$((currentScore + 1))
    else
      warn "$check_desc"
      resulttestjson "WARN"
      currentScore=$((currentScore - 1))
    fi
  else
    warn "$1 - test reference syntax invalid; Description: $2"
  fi
}
\#example_check_call(){
\#  make_check "1_2_3" "test check"
\#}


check_L1() {
  \# arg1 = id
  \# arg2 = descrition
  \# function initialises logit, puts info
  \# and startsectionjson
  logit ""
  id_L1=$1
  desc_L1=$2
  check_L1="$id_L1 - $desc_L1"
  info "$check_L1"
  startsectionjson "$id_L1" "$desc_L1"
}

check_L2() {
  \# arg1 = id
  \# arg2 = descrition
  \# function initialises logit, puts info
  logit ""
  id_L2=$(echo "$1" | sed -e "s/_/./g")
  desc_L2=$2
  check_L2="$id_L2 - $desc_L2"
  info "$check_L2"
}

`
