### ISSUE TITLE
Feature request: TAP output files

### ISSUE THREAD

**Issue by knaapjvd** [docker/docker-bench-security#509]
Not sure if this is the preferred method of filing a request for a new feature, but I would appreciate enhanced support for automated benchmark testing, in the form of Test Anything Protocol output files.

It would really help our pipeline automation if the options would include TAP output formatting.

**Comment by konstruktoid** [comment]
Hi @knaapjvd, thanks for the feature request. I'll have a look at what it takes to implement TAP output.

**Comment by konstruktoid** [comment]
Hi again @knaapjvd, I believe that adding TAP output is a great deal of work and requires rewriting the actual tests in order to make it work properly.

Writing the CIS Docker benchmark in e.g BATS is a better way if this functionality is required.

Currently JSON and text log is the supported logging.

**Comment by knaapjvd** [comment]
Ok, thanks for processing my request.
