### ISSUE TITLE
Fail to find docker daemon

### ISSUE THREAD

**Issue by gasgas4** [docker/docker-bench-security#90]
1. Run

docker run -it --net host --pid host --cap-add audit_control \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /etc:/etc --label docker_bench_security \
    docker/docker-bench-security

2. return

  Error connecting to docker daemon (does docker ps work?)

3. but docker ps and docker version all work
  
3.1 docker version

Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

**Comment by konstruktoid** [comment]
Hi @gasgas4 and thank you for reporting this.
Can you include the commands and results?
A cut and paste from you shell when you go through the steps would be great.

**Comment by konstruktoid** [comment]
Closing to to inactivity.

**Comment by PasqualePuzio** [comment]
Hi,

I'm experiencing the same issue.

After running this command

"docker run -i --net host --pid host --cap-add audit_control -v /var/lib:/var/lib -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc --label docker_bench_security docker/docker-bench-security"

I get the following error message

Error connecting to docker daemon (does docker ps work?)

However, I'm sure that docker is up and running (docker ps works correctly)

**Comment by PasqualePuzio** [comment]
And here's the output of docker version

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

**Comment by konstruktoid** [comment]
Hi @PasqualePuzio, I can't reproduce this running on Ubuntu. Could you please include some host details as well?

```sh
$ docker run -i --net host --pid host --cap-add audit_control -v /var/lib:/var/lib -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc --label docker_bench_security docker/docker-bench-security
Unable to find image 'docker/docker-bench-security:latest' locally
latest: Pulling from docker/docker-bench-security
56b26193e0fa: Pull complete
a3ed95caeb02: Pull complete
12e7059bd3f3: Pull complete
28bd87450f78: Pull complete
e9b909010d85: Pull complete
Digest: sha256:ada43131b626300b8c14ce95712c92e1d0efa5c8b5108c1495c0a6e522b2df81
Status: Downloaded newer image for docker/docker-bench-security:latest
# ------------------------------------------------------------------------------
# Docker Bench for Security v1.0.0
#
# Docker, Inc. (c) 2015
#
# Checks for dozens of common best-practices around deploying Docker containers in production.
# Inspired by the CIS Docker 1.6 Benchmark:
# https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf
# ------------------------------------------------------------------------------

Initializing Wed Feb 17 19:29:12 CET 2016


[INFO] 1 - Host Configuration
[WARN] 1.1  - Create a separate partition for containers
[PASS] 1.2  - Use an updated Linux Kernel
[PASS] 1.5  - Remove all non-essential services from the host - Network
[PASS] 1.6  - Keep Docker up to date
[INFO]       * Using 1.11.0 which is current as of 2016-02-11
[INFO]       * Check with your operating system vendor for support and security maintenance for docker
[INFO] 1.7  - Only allow trusted users to control Docker daemon
[INFO]      * docker:x:999:tsj
[WARN] 1.8  - Failed to inspect: auditctl command not found.

....
```

**Comment by PasqualePuzio** [comment]
Hi @konstruktoid 

here's the output of /proc/version

Linux version 2.6.32-5-amd64 (Debian 2.6.32-48squeeze14) (ben@decadent.org.uk) (gcc version 4.3.5 (Debian 4.3.5-4) ) #1 SMP Sat Sep 19 22:03:27 UTC 2015

FYI it's a VM on Amazon EC2

Thanks

**Comment by konstruktoid** [comment]
Does running the script work?

**Comment by PasqualePuzio** [comment]
Hi @konstruktoid,

yes, running the bash script works just fine. Any idea of what may be the cause of this issue?

Thanks

**Comment by konstruktoid** [comment]
Hi again @PasqualePuzio, tested various scenarios and older clients can't connect to newer server versions. 

Building the container with `ENV VERSION 1.9.0` or `ENV VERSION 1.9.1`, will hopefully make it work. 
Could you try building a test container to verify this on your system as well?

Reopening the issue, the only question is how far back we should go.

**Comment by PasqualePuzio** [comment]
Hi @konstruktoid,

where/how do I set that env variable? At which step of the build?

Thanks

**Comment by konstruktoid** [comment]
You can't modify a ENV when building an image, sorry to say. 
What I meant was that in order to fix this issue we need to change https://github.com/docker/docker-bench-security/blob/master/Dockerfile#L5 to an older version, but which version would be old enough?

**Comment by PasqualePuzio** [comment]
Got it. Let me give it a try. I'll keep you posted.

**Comment by PasqualePuzio** [comment]
Hi @konstruktoid 

after more investigation, the trick (changing the ENV VERSION value) seems to work only with the default Dockerfile. If I try to use the same trick on the Debian Dockerfile in the distros folder, I get the error message anyway.

Does it depend on the base image ?

Thanks

**Comment by konstruktoid** [comment]
The Debian dockerfile doesn't use an ENV to specify a version, instead it pulls Docker with ` curl -sSL https://get.docker.com/ | sh ` and thus get the latest stable version. The default Alpine Dockerfile uses ENV and curl (https://github.com/docker/docker-bench-security/blob/master/Dockerfile#L14-L15) to fetch the Docker binary.

**Comment by PasqualePuzio** [comment]
Got it. Thank you for the clarification.

What now? Should those Dockerfiles be fixed somehow? ;-)

**Comment by konstruktoid** [comment]
The problem is which (old version) to pick. 1.9.1 to cover Fedora 23 and openSuse? 1.6.2 to cover most Ubuntu versions? I believe RHEL includes 1.7.

Compare the following:
https://www.rpmfind.net/linux/rpm2html/search.php?query=docker&submit=Search+...&system=&arch=
https://packages.debian.org/search?searchon=names&keywords=docker.io
http://packages.ubuntu.com/search?keywords=docker.io&searchon=names&suite=all&section=all

**Comment by PasqualePuzio** [comment]
In my opinion, you should just enable the possibility to define the version to be used through the declaration of the VERSION env variable. Then it will be up to the user to set it according to its own local version of Docker

**Comment by konstruktoid** [comment]
True, that would be great. The problem is that you can't define a ENV in the build process, which means we have to include multiple versions of the binary in the image, in order to use the variable with `docker run`.
And even if we could define a ENV in the build process, we would have to build the image with multiple versions, and if you would like to build the image locally I believe it's easier just to modify the Dockerfile.

**Comment by PasqualePuzio** [comment]
Maybe I'm missong something, correct me if I'm wrong. Couldn't we just fix the distro-specific Dockerfiles in order to make them download and build docker the same way the default Dickerfile does? How difficult would this be? This way the user can choose the target docker version when building the image the same way he can do with the default Dockerfile, right? Thanks

**Comment by konstruktoid** [comment]
The distro-specific Dockerfile that breaks the norm is the `Dockerfile.debian` which uses the `curl | sh` method, the other Dockerfiles uses the docker version available in the default distro repositories.

If I change the `Dockerfile.debian` to just install the `docker.io` from the default repositories, you'll get the latest Debian supported docker version. This will most likely fix your issue.

If we modify the other distro-specific Dockerfiles to use  `curl | sh`, we'll mostly likely end up in the same situation you're in where there's a server/client version mismatch.

If you want the ENV VERSION variant as in the alpine Dockerfile, I'm not really seeing the point of modifying the distro-specific Dockerfiles, since you could just edit the `ENV VERSION` in the default Dockerfile if you're building the image yourself.

Making sense, or am I missing something?

**Comment by PasqualePuzio** [comment]
Makes completely sense. Most likely just fixing the Docker.debian Dockerfile will be enough to fix this issue (which is not only mine btw). Could you please do that?

If that works I don't see the point of having the ENV VERSION variant, as you said.

Thanks

**Comment by konstruktoid** [comment]
Could you try the dockerfile in https://github.com/konstruktoid/docker-bench-security/blob/issue90/distros/Dockerfile.debian?

**Comment by PasqualePuzio** [comment]
Hi @konstruktoid 

I confirm that dockerfile in https://github.com/konstruktoid/docker-bench-security/blob/issue90/distros/Dockerfile.debian works.

Could you please explain why ? I can see that it doesn't download docker and it's based on debian stretch.

Thanks

**Comment by konstruktoid** [comment]
Thanks for testing @PasqualePuzio, it does download Docker, it's called `docker.io` in Debian since docker is a _system tray for KDE3/GNOME2 docklet applications_ (https://packages.debian.org/stretch/docker). I use `stretch` because it's the most stable Debian release that actually include the Docker package.

**Comment by PasqualePuzio** [comment]
Got it. Thank you very much. Would you mind to commit this Dockerfile ? Thanks

**Comment by konstruktoid** [comment]
Merged.
